# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:
    - name: launching AWS instance using Ansible
      ec2:
        instance_type: t2.medium
        image: ami-04137ed1a354f54c4
        region: eu-west-1
        wait: yes
        count: 3
        assign_public_ip: yes
        aws_access_key: <AWS_ACC_KEY>
        aws_secret_key: <AWS_SEC_KEY>
        group: <SECURITY_GROUP>
        key_name: <KEY-NAME>
        vpc_subnet_id: <SUBNET_ID>
