- hosts: master
  become: yes
  tasks:
    - name: check kube
      apt:
        name: kubectl
        state: present
        force: yes

    - name: pull from git
      k8s:
        state: present
        src: https://raw.githubusercontent.com/ameeno/cogito-deployment-kube/master/kube.yaml
