- hosts: master
  become: yes
  become_user: ubuntu
  tasks:
    - name: check kube
      apt:
        name: kubectl
        state: present
        force: yes

    - name: Download yml config
      get_url:
        url: https://raw.githubusercontent.com/ameeno/cogito-deployment-kube/master/kube.yaml
        dest: /home/ubuntu/kube.yml

    - name: pull from git
      k8s:
        state: present
        src: /home/ubuntu/kube.yml
